#Bag Of Words

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('spam_dataset.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts() #shows the count of unique values in the column 'Category'

Category
ham     4825
spam     747
Name: count, dtype: int64

Below is the function, that we would pass into the pandas function 'apply', to create a column for representing spam/ham data in form of 0s and 1s

In [ ]:
def spam_number(x):
  if x == 'spam':
    return 1
  return 0

Creating a column 'spam' in our dataframe to act as our 'y' data

In [ ]:
df['spam'] = df.Category.apply(spam_number)

In [ ]:
df.head(10)

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
5     spam  FreeMsg Hey there darling it's been 3 week's n...     1
6      ham  Even my brother is not like to speak with me. ...     0
7      ham  As per your request 'Melle Melle (Oru Minnamin...     0
8     spam  WINNER!! As a valued network customer you have...     1
9     spam  Had your mobile 11 months or more? U R entitle...     1

Splitting the data into 2 parts - Train and Test

X - question, y - answer

In [ ]:
df.shape

(5572, 3)

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [ ]:
X_train

1459    Fighting with the world is easy, u either win ...
678     Piggy, r u awake? I bet u're still sleeping. I...
1392                  Haha just kidding, papa needs drugs
4224                      Stupid auto correct on my phone
4906    Warner Village 83118 C Colin Farrell in SWAT t...
                              ...                        
3122     Small problem in auction:)punj now asking tiwary
3790    Are you sure you don't mean "get here, we made...
5048                      Hmmm.still we dont have opener?
1211            Guessin you ain't gonna be here before 9?
427                           aathi..where are you dear..
Name: Message, Length: 4457, dtype: object

In [ ]:
y_train[:4][1459]

np.int64(0)

In [ ]:
X_train

1459    Fighting with the world is easy, u either win ...
678     Piggy, r u awake? I bet u're still sleeping. I...
1392                  Haha just kidding, papa needs drugs
4224                      Stupid auto correct on my phone
4906    Warner Village 83118 C Colin Farrell in SWAT t...
                              ...                        
3122     Small problem in auction:)punj now asking tiwary
3790    Are you sure you don't mean "get here, we made...
5048                      Hmmm.still we dont have opener?
1211            Guessin you ain't gonna be here before 9?
427                           aathi..where are you dear..
Name: Message, Length: 4457, dtype: object

In [ ]:
X_train.values #converting a pandas series into a numpy array

array(['Fighting with the world is easy, u either win or lose bt fightng with some1 who is close to u is dificult if u lose - u lose if u win - u still lose.',
       "Piggy, r u awake? I bet u're still sleeping. I'm going 4 lunch now...",
       'Haha just kidding, papa needs drugs', ...,
       'Hmmm.still we dont have opener?',
       "Guessin you ain't gonna be here before 9?",
       'aathi..where are you dear..'], dtype=object)

In [ ]:
type(X_train.values)

numpy.ndarray

In [ ]:
X_train_np_array = X_train.values

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X_train_cv = cv.fit_transform(X_train_np_array) # The CountVectorizer model expects a numpy array instead of a pandas dataframe/series

Getting a look at the vocabulary we have generated

In [ ]:
cv.get_feature_names_out()[1000:2000]

array(['anythin', 'anything', 'anythingtomorrow', 'anytime', 'anyway',
       'anyways', 'anywhere', 'apart', 'apartment', 'apes', 'aphex',
       'apnt', 'apo', 'apologetic', 'apologise', 'apologize', 'apology',
       'app', 'apparently', 'appear', 'appendix', 'applausestore',
       'applebees', 'apples', 'application', 'apply', 'applyed',
       'applying', 'appointment', 'appreciate', 'appreciated',
       'approaches', 'appropriate', 'approve', 'approved', 'approx',
       'apps', 'appt', 'appy', 'april', 'aproach', 'apt', 'aptitude',
       'ar', 'arab', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'arestaurant', 'aretaking', 'areyouunique', 'argentina',
       'argh', 'argue', 'arguing', 'argument', 'arguments', 'aries',
       'arise', 'arises', 'arithmetic', 'arm', 'armand', 'armenia',
       'arms', 'arng', 'arngd', 'arnt', 'around', 'aroundn', 'arr',
       'arrange', 'arranging', 'arrested', 'arrival', 'arrive', 'arrived',
       'arrow', 'arsenal', '

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
cv.vocabulary_

{'fighting': 2828,
 'with': 7526,
 'the': 6790,
 'world': 7576,
 'is': 3741,
 'easy': 2508,
 'either': 2548,
 'win': 7498,
 'or': 4969,
 'lose': 4198,
 'bt': 1549,
 'fightng': 2829,
 'some1': 6284,
 'who': 7474,
 'close': 1852,
 'to': 6911,
 'dificult': 2311,
 'if': 3595,
 'still': 6468,
 'piggy': 5209,
 'awake': 1174,
 'bet': 1335,
 're': 5583,
 'sleeping': 6212,
 'going': 3164,
 'lunch': 4251,
 'now': 4835,
 'haha': 3285,
 'just': 3869,
 'kidding': 3925,
 'papa': 5066,
 'needs': 4728,
 'drugs': 2461,
 'stupid': 6532,
 'auto': 1156,
 'correct': 2013,
 'on': 4930,
 'my': 4658,
 'phone': 5183,
 'warner': 7368,
 'village': 7273,
 '83118': 666,
 'colin': 1888,
 'farrell': 2775,
 'in': 3635,
 'swat': 6633,
 'this': 6830,
 'wkend': 7535,
 'get': 3109,
 'free': 2976,
 'med': 4410,
 'popcorn': 5303,
 'show': 6125,
 'msg': 4609,
 'ticket': 6868,
 'kiosk': 3939,
 'valid': 7217,
 '12': 283,
 'reply': 5713,
 'sony': 6306,
 'mre': 4605,
 'film': 2839,
 'offers': 4896,
 'love': 4216,
 'little': 414

In [ ]:
type(X_train_cv)

Converting a scipy matrix into a numpy array

In [ ]:
X_train_np = X_train_cv.toarray()

In [ ]:
X_train_np.shape

(4457, 7724)

In [ ]:
np.where(X_train_np[1]!=0)

(array([1174, 1335, 3164, 4251, 4835, 5209, 5583, 6212, 6468]),)

In [ ]:
cv.get_feature_names_out()[6468]

'still'

In [ ]:
X_train[0:4]

1459    Fighting with the world is easy, u either win ...
678     Piggy, r u awake? I bet u're still sleeping. I...
1392                  Haha just kidding, papa needs drugs
4224                      Stupid auto correct on my phone
Name: Message, dtype: object

In [ ]:
X_train[0:4][678]

"Piggy, r u awake? I bet u're still sleeping. I'm going 4 lunch now..."

In [ ]:
X_train_np[0][755]

In [ ]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
nb_model = MultinomialNB()
nb_model.fit(X_train_cv,y_train)

MultinomialNB()

In [ ]:
X_test_cv = cv.transform(X_test)

In [ ]:
from sklearn.metrics import classification_report

y_pred = nb_model.predict(X_test_cv)

#getting a classfication report on the model's potency
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       962
           1       0.97      0.90      0.93       153

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
y_pred_ten = nb_model.predict(X_test_cv[0:10])

In [ ]:
y_pred_ten

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0])

In [ ]:
y_test[0:10]

3830    0
5268    0
3986    0
1365    0
2211    0
5330    0
2641    0
3792    1
3817    0
5452    0
Name: spam, dtype: int64